
services:
  visitors_app:
    container_name: visitors_app
    image: visitors_app:0.0.1
    build: ..
    ports:
      - "4000:4000"
    environment:
      - DB_URL=postgresql://postgres:postgres@visitors_db:5432/postgres
    depends_on:
      - visitors_db
  visitors_db:
    container_name: visitors_db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
